# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.21.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(a.size*a.itemsize)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info

<function numpy.info(object=None, maxwidth=76, output=<ipykernel.iostream.OutStream object at 0x0000022008887190>, toplevel='numpy')>

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
b = b[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
a = np.arange(0,9)
a = a.reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = [1,2,0,0,4,0]
b = np.nonzero(a)
b

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random([3,3,3])

array([[[0.84783138, 0.90706608, 0.02252821],
        [0.79060864, 0.86303567, 0.12640899],
        [0.83211341, 0.16344438, 0.10219483]],

       [[0.62422759, 0.99333636, 0.67679753],
        [0.47199874, 0.10442188, 0.10818035],
        [0.05243039, 0.84930291, 0.65433159]],

       [[0.67208757, 0.76649931, 0.48019911],
        [0.55872554, 0.37721079, 0.17656708],
        [0.18574022, 0.02053827, 0.36807108]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random([10,10])
a.min(), a.max()

(0.002301417328424704, 0.9819260854738071)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
a = np.random.random(30)
a.mean()

0.4832797226154893

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((5,5))
a = np.pad(a, pad_width=1)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
a = np.diag(1+np.arange(4),-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8,8))
a[::2,::2] = 1
a[1::2,1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
b = np.unravel_index(99,(6,7,8))
b

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.tile([[1,0],[0,1]],(4,4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.random((5,5))
a = (a - np.mean(a)) / (np.std (a))
a

array([[ 0.74580285, -1.61781266,  0.82964781,  0.36254442,  0.96147709],
       [ 1.14542952,  0.50854116, -1.08606966, -0.0591702 ,  1.25555252],
       [-0.37520552,  0.15772888,  1.13595067,  0.68650141,  0.87177331],
       [-0.48859731, -0.44686574,  0.97194611,  0.56576608,  0.84816277],
       [-1.25591096, -1.81642954, -1.20895831, -0.76234073, -1.92946398]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
colour = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.random((5,3))
b = np.random.random((3,2))
c = np.dot(a,b)
print(a)
print(b)
print(c)

[[0.86533982 0.86135616 0.35845597]
 [0.37237281 0.88224406 0.12642535]
 [0.84108693 0.60489016 0.90877676]
 [0.20779818 0.45270877 0.5378569 ]
 [0.47883267 0.57394424 0.68286127]]
[[0.5220993  0.08948237]
 [0.12384164 0.96093544]
 [0.67277892 0.76975539]]
[[0.79962669 1.18106373]
 [0.38873044 0.97841698]
 [1.12544734 1.35605866]
 [0.52641427 0.86763643]
 [0.78049106 1.12000658]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.random.random(10)
a = 10*a
print(a)
a[(3 < a) & (a < 8)] *= -1
print(a)

[3.8706195  4.41699902 9.41577245 7.06897984 5.81819138 1.79175702
 8.12233068 4.38456758 9.33993106 2.91512206]
[-3.8706195  -4.41699902  9.41577245 -7.06897984 -5.81819138  1.79175702
  8.12233068 -4.38456758  9.33993106  2.91512206]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))

print(np.sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
print('The last one')

The last one


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-29-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-29-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
a = np.random.uniform(-10,+10,10)
print(a)
print(np.ceil(a))

[-6.08338815  1.58395458 -5.39559162 -7.62878187  7.90885009 -5.16753126
 -9.46139304  7.12795892  4.25525889  6.61465847]
[-6.  2. -5. -7.  8. -5. -9.  8.  5.  7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[3 4 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
defaults = np.seterr(all="ignore")
# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
print(False)

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1))

2021-09-09
2021-09-10
2021-09-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
a = []
for i in range(31):
    a.append(np.datetime64('2016-07-01') + i*np.timedelta64(1))
print(a)

[numpy.datetime64('2016-07-01'), numpy.datetime64('2016-07-02'), numpy.datetime64('2016-07-03'), numpy.datetime64('2016-07-04'), numpy.datetime64('2016-07-05'), numpy.datetime64('2016-07-06'), numpy.datetime64('2016-07-07'), numpy.datetime64('2016-07-08'), numpy.datetime64('2016-07-09'), numpy.datetime64('2016-07-10'), numpy.datetime64('2016-07-11'), numpy.datetime64('2016-07-12'), numpy.datetime64('2016-07-13'), numpy.datetime64('2016-07-14'), numpy.datetime64('2016-07-15'), numpy.datetime64('2016-07-16'), numpy.datetime64('2016-07-17'), numpy.datetime64('2016-07-18'), numpy.datetime64('2016-07-19'), numpy.datetime64('2016-07-20'), numpy.datetime64('2016-07-21'), numpy.datetime64('2016-07-22'), numpy.datetime64('2016-07-23'), numpy.datetime64('2016-07-24'), numpy.datetime64('2016-07-25'), numpy.datetime64('2016-07-26'), numpy.datetime64('2016-07-27'), numpy.datetime64('2016-07-28'), numpy.datetime64('2016-07-29'), numpy.datetime64('2016-07-30'), numpy.datetime64('2016-07-31')]


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
a = np.ones(5)
b = 2*np.ones(5)
b = a+b
print(-(a/2)*b)

[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
a = np.random.uniform(0,10,10)
print(a)
print()

print(np.floor(a))
print(a // 1)
print(a - a%1)
print(np.trunc(a))

[6.96137202 9.06878448 3.48641117 1.10709897 3.38610684 1.30630907
 8.44450519 0.8448691  2.39951929 6.90320677]

[6. 9. 3. 1. 3. 1. 8. 0. 2. 6.]
[6. 9. 3. 1. 3. 1. 8. 0. 2. 6.]
[6. 9. 3. 1. 3. 1. 8. 0. 2. 6.]
[6. 9. 3. 1. 3. 1. 8. 0. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def gen():
    for x in range(10):
        yield x

a = np.fromiter(gen(),dtype=int)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
a = np.random.uniform(0,1,10)
a

array([0.68424009, 0.38878012, 0.31632008, 0.79386686, 0.29074909,
       0.27059395, 0.36268535, 0.89412594, 0.28666294, 0.73112075])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
a = np.random.random(10)
a.sort()
a

array([0.18521488, 0.38637198, 0.41826399, 0.4713978 , 0.49586389,
       0.66369242, 0.67143593, 0.78389687, 0.88608898, 0.89671288])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
a = np.arange(10)
print(a)
np.add.reduce(a)

[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
A = np.random.randint(0,2,6)
B = np.random.randint(0,2,6)

c = np.array_equal(A,B)
c

False

#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
a = np.random.uniform(0,1,10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.sqrt(x**2+y**2)
θ = np.arctan2(x,y)
b = list(zip(r,θ))
print(b)

[(0.8972920926163426, 0.4840703713542796), (0.6066893669472595, 0.33366217557199235), (1.1439357858849861, 0.8062602918686511), (0.8124740149910538, 1.498237378792076), (0.4764904606328513, 0.8984180099556741), (0.5205859472684597, 0.5840199735042504), (0.06381206866524518, 1.2420867742321262), (0.6638088082818203, 0.12839878914107447), (1.1633481212237484, 0.7355579434580821), (0.07684733529795572, 0.9908572798442153)]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
a = np.random.random(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.1550691  0.38070272 0.86173069 0.7561017  0.10241824 0.57981476
 0.99638477 0.03722771 0.64323273 0.8001063 ]
[0.1550691  0.38070272 0.86173069 0.7561017  0.10241824 0.57981476
 0.         0.03722771 0.64323273 0.8001063 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
a = np.zeros((5,5), [('x',float),('y',float)])
print(a)
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
x = np.arange(1,5)
print(x)
y = x + 1.5
c = 1.0 / np.subtract.outer(x, y)
print(c)

[1 2 3 4]
[[-0.66666667 -0.4        -0.28571429 -0.22222222]
 [-2.         -0.66666667 -0.4        -0.28571429]
 [ 2.         -2.         -0.66666667 -0.4       ]
 [ 0.66666667  2.         -2.         -0.66666667]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [49]:
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
a = np.arange(100)
r = np.random.uniform(0,100)
i = (np.abs(a-r)).argmin()
print(a[i])

78


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
a = np.zeros(5, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


<ipython-input-51-265fecdb9fc4>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(5, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [52]:
from io import StringIO

# Fake file
f = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
a = np.genfromtxt(f, dtype=int, delimiter=",")
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [53]:
a = np.arange(10).reshape(5,2)
for i, val in np.ndenumerate(a):
    print(i, val)

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [54]:
n = 7
p = 5
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [55]:
x = np.random.rand(3, 6)

y = x - x.mean(axis=1, keepdims=True)

print(y)

[[-0.47083858  0.46898752 -0.43706386  0.42924349 -0.10912465  0.11879608]
 [ 0.07198333  0.13935376 -0.11477667  0.23489776 -0.53955009  0.20809191]
 [ 0.26911923  0.26784659 -0.08093599 -0.14659003 -0.0505072  -0.25893258]]


#### 59. How to sort an array by the nth column? (★★☆)

In [56]:
a = np.random.randint(0,10,(4,4))
print(a)
print(a[a[:,1].argsort()])

[[4 5 5 9]
 [1 3 4 1]
 [4 3 9 6]
 [8 5 6 6]]
[[1 3 4 1]
 [4 3 9 6]
 [4 5 5 9]
 [8 5 6 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [57]:
a = np.random.uniform(0,1,10)
c = 0.5
b = a[np.abs(a - c).argmin()]
print(a)
print(b)

[0.89974543 0.51274858 0.14279702 0.61139578 0.26418758 0.97810135
 0.7816246  0.80448421 0.72471642 0.70288904]
0.5127485798083292


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

In [58]:
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
a = NameArray(np.arange(10), "range_10")
print(a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [59]:
X = np.arange(5)
print(X)
I = [1,5,3,8,2]
F = np.bincount(I,X)
print(F)

[0 1 2 3 4]
[0. 0. 4. 2. 0. 1. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [60]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))

np.diag(np.dot(a, b))

array([1.62061505, 2.22945778, 1.04732222, 0.62069251, 0.97428397])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [61]:
a = np.arange(16).reshape(4,4)
a[[1,3]] = a[[3,1]]
print(a)

[[ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [62]:
a = np.random.randint(0,2,10)
print(a)
a = np.logical_not(a)
print(a)

b = np.random.uniform(-1.0,1.0,10)
print(b)
b = np.negative(b)
print(b)

[1 0 1 1 0 0 0 0 1 1]
[False  True False False  True  True  True  True False False]
[-0.49913045 -0.05664067 -0.89066876 -0.68431037  0.63798443  0.96974632
 -0.6039106  -0.81161175 -0.62792522  0.56972685]
[ 0.49913045  0.05664067  0.89066876  0.68431037 -0.63798443 -0.96974632
  0.6039106   0.81161175  0.62792522 -0.56972685]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [63]:
a = np.random.uniform(0,1,(5,5))
u, s, v = np.linalg.svd(a)
rank = np.sum(s > 1e-10)
print(rank)

5


#### 83. How to find the most frequent value in an array?

In [64]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[5 7 1 8 7 0 2 0 0 1 6 0 9 6 2 6 7 5 1 7 6 1 2 3 7 9 4 5 5 8 4 7 1 2 5 6 3
 4 1 0 3 8 2 5 1 8 3 8 2 8]
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [65]:
a = np.arange(100)
np.random.shuffle(a)
n = 7

print (a[np.argsort(a)[-n:]])

[93 94 95 96 97 98 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [66]:
x = np.random.rand(int(1e5))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.49 ms ± 273 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.2 ms ± 196 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
126 µs ± 1.16 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [67]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A)) # sum
print(np.einsum('i,i->i', A, B)) # A*B
print(np.einsum('i,i', A, B)) # inner product
print(np.einsum('i,j->ij', A, B)) # outer product

6.312341958906677
[0.32082258 0.12908587 0.86853605 0.02715589 0.76121995 0.61311504
 0.38792884 0.1558123  0.2830552  0.43742026]
3.9841519744400107
[[0.32082258 0.1021553  0.45429143 0.06018078 0.41827045 0.32848968
  0.40916603 0.37843637 0.22662609 0.27604956]
 [0.40539905 0.12908587 0.57405348 0.07604586 0.5285365  0.41508739
  0.51703193 0.47820121 0.28637012 0.3488228 ]
 [0.61336392 0.19530539 0.86853605 0.11505649 0.79966942 0.62802226
  0.78226314 0.72351273 0.43327457 0.52776473]
 [0.14476751 0.04609641 0.2049938  0.02715589 0.18873974 0.1482272
  0.18463147 0.17076507 0.10226242 0.1245642 ]
 [0.58387234 0.18591477 0.82677536 0.10952437 0.76121995 0.59782588
  0.7446506  0.688725   0.412442   0.5023889 ]
 [0.59880464 0.19066947 0.8479198  0.11232541 0.78068784 0.61311504
  0.76369474 0.70633887 0.42299003 0.51523729]
 [0.30417073 0.09685308 0.43071208 0.05705718 0.39656071 0.31143989
  0.38792884 0.35879417 0.21486338 0.2617216 ]
 [0.13209117 0.04206005 0.18704384 0.02477802 

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [68]:
x = [[1.0, 0.0, 3.0, 8.0], [2.0, 0.0, 1.0, 1.0], [1.5, 2.5, 1.0, 0.0]]
y = []
n = 4
for i in range(2):
    if(sum(x[i])==n):
        y.append(x[i])
y

[[2.0, 0.0, 1.0, 1.0]]

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)